### ISSUE TITLE
Because tensorflow depends on binary >=0.0.1 which requires SDK version >=1.8.0 <2.0.0, version solving failed

### ISSUE THREAD

**Issue by manyopensource** [thosakwe/tensorflow.dart#4]

**Comment by thosakwe** [comment]
1. It doesn't depend on `package:binary`, so not sure why you're getting this error.
2. You should send a PR. This library isn't maintained much anymore, because the Tensorflow C API lacks functionality + documentation.

**Comment by manyopensource** [comment]
Hi @thosakwe! Can you make an article or something where you'll explain everything about tensorflow package? I know you'll say "why on Earth you would need that", but I tried.
