### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by manyopensource** [thosakwe/tensorflow.dart#5]
flutter pub get
Running "flutter pub get" in somemlproject...                     
The current Dart SDK version is 2.8.4.

Because every version of tensorflow depends on protobuf >=0.2.0 <=0.9.0 which requires SDK version >=0.7.5 <2.0.0-∞, tensorflow is forbidden.

So, because somemlproject depends on tensorflow ^0.0.0, version solving failed.
pub get failed (1; So, because somemlproject depends on tensorflow ^0.0.0, version solving failed.)
exit code 1

**Comment by thosakwe** [comment]
I'm not actively maintaining this project, and will probably archive it. But you can add the correct version of `protobuf` to your `dependency_overrides`.
